package betaps.display;

import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Vignesh
 */
public class AboutMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form AboutMenuPanel
     */
    public AboutMenuPanel() {
        initComponents();
        loadLogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        About_IconPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(240, 200));
        setMinimumSize(new java.awt.Dimension(240, 200));
        setPreferredSize(new java.awt.Dimension(240, 200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        About_IconPanel.setMaximumSize(new java.awt.Dimension(200, 87));
        About_IconPanel.setMinimumSize(new java.awt.Dimension(200, 87));
        About_IconPanel.setPreferredSize(new java.awt.Dimension(200, 87));

        javax.swing.GroupLayout About_IconPanelLayout = new javax.swing.GroupLayout(About_IconPanel);
        About_IconPanel.setLayout(About_IconPanelLayout);
        About_IconPanelLayout.setHorizontalGroup(
            About_IconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        About_IconPanelLayout.setVerticalGroup(
            About_IconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
        );

        add(About_IconPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Exo 2 Light", 0, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Licensed to - Beta Public School\n  Vignesh DV | Copyright - 2014");
        jTextArea1.setMaximumSize(new java.awt.Dimension(200, 87));
        jTextArea1.setMinimumSize(new java.awt.Dimension(200, 87));
        jTextArea1.setPreferredSize(new java.awt.Dimension(200, 87));
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 180, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void loadLogo() {
        try {
            About_IconPanel.setLayout(new BorderLayout());
            BufferedImage myLogo = ImageIO.read(getClass().getResource("/betaps/res/Logo_For_Soft.png"));
            JLabel myLogoLabel = new JLabel(new ImageIcon(myLogo));
            
            About_IconPanel.add(myLogoLabel, BorderLayout.CENTER);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel About_IconPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
