/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package betaps.display;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Vignesh
 */
public class DefaultPanel extends javax.swing.JPanel {

    /**
     * Creates new form DefaultPanel
     */
    public DefaultPanel() {
        initComponents();
        updateDateLabel();
    }
    
    public void updateDateLabel(){
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd'th' MMMM, yyyy");
        DateContentLabel.setText(sdf.format(date));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        DateContentLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 579));
        setMinimumSize(new java.awt.Dimension(800, 579));
        setName("card0"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 579));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeLabel.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(153, 153, 153));
        WelcomeLabel.setText("Welcome to Record Keeper");
        add(WelcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        DateLabel.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        DateLabel.setForeground(new java.awt.Color(153, 153, 153));
        DateLabel.setText("Today's Date: ");
        add(DateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        DateContentLabel.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        DateContentLabel.setForeground(new java.awt.Color(153, 153, 153));
        DateContentLabel.setPreferredSize(new java.awt.Dimension(100, 16));
        add(DateContentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        getAccessibleContext().setAccessibleName("card0");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateContentLabel;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel WelcomeLabel;
    // End of variables declaration//GEN-END:variables
}
